### ISSUE TITLE
Not determined 'sandboxed-fs'

### ISSUE THREAD

**Issue by legioner9** [HowProgrammingWorks/DependencyInjection#2]
https://github.com/HowProgrammingWorks/DependencyInjection/blob/fad3917b2a2be39e1bcb04039936489b59f80464/JavaScript/framework.js#L11
Error: Cannot find module 'sandboxed-fs'

**Comment by tshemsedinov** [comment]
You need to install dependencies, before running `node framework.js` use `npm i`
